# Generated by Django 6.0.1 on 2026-01-15 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('conteudo', models.TextField(help_text='Use variáveis como {nome_cliente}, {cpf_cliente}, {valor_total} para substituição automática.')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_final', models.TextField(blank=True, null=True, verbose_name='Texto do Contrato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERADO', 'Gerado (Aguardando Assinatura)'), ('ASSINADO', 'Assinado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='producao.pedido')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juridico.modelocontrato')),
            ],
        ),
    ]
