# Generated by Django 6.0.1 on 2026-01-15 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='producao.pedido'),
        ),
    ]
