# Generated by Django 6.0.1 on 2026-01-15 00:09

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas_reais', models.JSONField(blank=True, default=dict, verbose_name='Medidas Reais (Cliente)')),
                ('descricao_visual', models.TextField(verbose_name='Descrição do Modelo')),
                ('croqui_imagem', models.ImageField(blank=True, null=True, upload_to='croquis/')),
            ],
            options={
                'verbose_name': 'Definição Técnica',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('unidade', models.CharField(choices=[('M', 'Metros'), ('UN', 'Unidade'), ('KG', 'Quilos')], default='M', max_length=5)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Materiais (Estoque)',
            },
        ),
        migrations.CreateModel(
            name='ParametrosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_hora_padrao', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=10, verbose_name='Custo Hora (MO)')),
                ('taxa_imposto_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5, verbose_name='Imposto Padrão (Dec)')),
                ('custo_fixo_mensal', models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10, verbose_name='Custo Fixo Mensal')),
                ('meta_clientes_mes', models.DecimalField(decimal_places=0, default=Decimal('80'), max_digits=5, verbose_name='Meta Clientes/Mês')),
                ('margem_lucro_meta', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=5, verbose_name='Margem Lucro Alvo')),
            ],
            options={
                'verbose_name': 'Parâmetros do Sistema',
                'verbose_name_plural': '⚙️ Configurações Globais',
            },
        ),
        migrations.CreateModel(
            name='TemplateMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('estrutura_medidas', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Template de Medida',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPedido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_contrato', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('data_pedido', models.DateTimeField(blank=True, editable=False)),
                ('prazo_entrega', models.DateField()),
                ('status', models.CharField(choices=[('ORCAMENTO', '1. Orçamento'), ('APROVADO', '2. Aprovado (Financeiro OK)'), ('COMPRA', '3. Em Compras (Aguardando Material)'), ('CONFEC', '4. Em Confecção'), ('PROVA', '5. Em Provas'), ('ENTREGUE', '6. Entregue'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=20)),
                ('custo_hora_frozen', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('taxa_imposto_frozen', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('custo_fixo_frozen', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('meta_clientes_frozen', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=5, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade (Peças)')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas/Peça')),
                ('custo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete/Peça')),
                ('preco_manual_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário (Manual)')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_sinal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sinal Pago')),
                ('autorizado_gerencia', models.BooleanField(default=False, verbose_name='Autorizar Margem Baixa')),
                ('qtd_parcelas', models.PositiveIntegerField(default=1, verbose_name='Qtd Parcelas (Restante)')),
                ('dias_intervalo', models.PositiveIntegerField(default=30, verbose_name='Dias entre parcelas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total do Contrato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pedido',
                'verbose_name_plural': 'historical pedidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Unitário')),
                ('custo_calculado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_usados', to='producao.fichatecnica')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.material')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMovimentacaoEstoque',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Compra)'), ('S', 'Saída (Produção)')], max_length=1)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateTimeField(blank=True, editable=False)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producao.material')),
            ],
            options={
                'verbose_name': 'historical movimentacao estoque',
                'verbose_name_plural': 'historical movimentacao estoques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Compra)'), ('S', 'Saída (Produção)')], max_length=1)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='producao.material')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('prazo_entrega', models.DateField()),
                ('status', models.CharField(choices=[('ORCAMENTO', '1. Orçamento'), ('APROVADO', '2. Aprovado (Financeiro OK)'), ('COMPRA', '3. Em Compras (Aguardando Material)'), ('CONFEC', '4. Em Confecção'), ('PROVA', '5. Em Provas'), ('ENTREGUE', '6. Entregue'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=20)),
                ('custo_hora_frozen', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('taxa_imposto_frozen', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('custo_fixo_frozen', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('meta_clientes_frozen', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=5, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade (Peças)')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas/Peça')),
                ('custo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete/Peça')),
                ('preco_manual_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário (Manual)')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_sinal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sinal Pago')),
                ('autorizado_gerencia', models.BooleanField(default=False, verbose_name='Autorizar Margem Baixa')),
                ('qtd_parcelas', models.PositiveIntegerField(default=1, verbose_name='Qtd Parcelas (Restante)')),
                ('dias_intervalo', models.PositiveIntegerField(default=30, verbose_name='Dias entre parcelas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total do Contrato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='producao.pedido'),
        ),
        migrations.CreateModel(
            name='RegistroProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateTimeField()),
                ('realizada', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('1_PROVA', '1ª Prova (Estrutura)'), ('2_PROVA', '2ª Prova (Caimento)'), ('FINAL', 'Entrega Final'), ('AJUSTE', 'Ajustes')], default='1_PROVA', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='producao.pedido')),
            ],
            options={
                'ordering': ['data_agendada'],
            },
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.templatemedida', verbose_name='Manequim Base'),
        ),
    ]
