# Generated by Django 6.0.1 on 2026-01-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_fichatecnica_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='tempo_estimado_horas',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantas horas leva para produzir uma peça?', max_digits=5, verbose_name='Tempo Estimado (Horas)'),
        ),
    ]
