# Generated by Django 6.0.1 on 2026-01-15 21:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_fichatecnica_tempo_estimado_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrossistema',
            name='custo_fixo_mensal',
        ),
        migrations.RemoveField(
            model_name='parametrossistema',
            name='custo_hora_padrao',
        ),
        migrations.RemoveField(
            model_name='parametrossistema',
            name='meta_clientes_mes',
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='custo_agua',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='Água'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='custo_aluguel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Aluguel do Ateliê'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='custo_diarista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Diarista/Limpeza'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='custo_energia',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10, verbose_name='Energia Elétrica'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='custo_internet',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='Internet'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='custo_software',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10, verbose_name='Software/Assinaturas'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='eficiencia_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=3, verbose_name='Eficiência (Ex: 0.80)'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='horas_mensais_disponiveis',
            field=models.PositiveIntegerField(default=176, verbose_name='Horas Totais/Mês'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='pro_labore_meta',
            field=models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=10, verbose_name='Pró-labore Desejado'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='tempo_estimado_horas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tempo Estimado (Horas)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='taxa_imposto_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5, verbose_name='Imposto (Dec)'),
        ),
    ]
